version: '3'

services:
  next-app:
    image: learn-english
    container_name: app
    build: 
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - MONGO_URL=mongodb://database:27017/database



  database:
    image: mongo:5.0.0
    container_name: database
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db