services:
  next:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: next
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - database

  database:
    image: mongo:5.0.0
    container_name: database
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db