version: '3.9'

services:
  web:
    image: learn-english
    container_name: web
    build:
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    

  database:
    image: mongo:5.0.0
    container_name: database
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db