import { IList } from "../interface"


const lists: IList[] = [
    {
        name: "1. Verbos Regulares",
        icon: "⛹️",
        words: [
            { english: "divide", spanish: "dividir", points: 3, image: "https://i.giphy.com/media/6PDD11h741IpG/200w.webp" },
            { english: "support", spanish: "soportar", points: 3, image: "https://i.giphy.com/media/ew8hN0QnkoaOdTn2Eo/200w.webp" },
            { english: "follow", spanish: "seguir", points: 3, image: "https://i.giphy.com/media/TisFptjsMKzYp1fAzo/200w.webp" },
            { english: "complete", spanish: "completar", points: 3, image: "https://i.giphy.com/media/Q5RiiXiUWWVjvE3rER/200w.webp" },
            { english: "suck", spanish: "chupar", points: 3, image: "https://i.giphy.com/media/FnxHqXpcyYN32/200w.webp" },
            { english: "pull", spanish: "halar - tirar de", points: 3, image: "https://i.giphy.com/media/SsIZAm4IDC6yUQMa45/200w.webp" },
            { english: "practice", spanish: "practicar", points: 3, image: "https://i.giphy.com/media/xT9DPjkNXsQuoZva6c/200w.webp" },
            { english: "lower", spanish: "bajar - reducir - disminuir", points: 3, image: "https://i.giphy.com/media/g8tLOZ6RWlDvRf5Kfp/200w.webp" },
            { english: "kiss", spanish: "besar", points: 3, image: "https://i.giphy.com/media/l2Je2M4Nfrit0L7sQ/200w.webp" },
            { english: "wed", spanish: "casar(se) - unirse con", points: 3, image: "https://i.giphy.com/media/urgh3QkW9wgG8goYCQ/200w.webp" },
            { english: "smile", spanish: "sonreir", points: 3, image: "https://i.giphy.com/media/QTrG6mjkHEkpFR3DqX/200w.webp" },
            { english: "fish", spanish: "pescar", points: 3, image: "https://i.giphy.com/media/Xy0VPXTENJyG2HFqtr/200w.webp" },
            { english: "rest", spanish: "descansar - reposar", points: 3, image: "https://i.giphy.com/media/fdlcvptCs4qsM/200w.webp" },
            { english: "warm", spanish: "calentar(se) - recalentar", points: 3, image: "https://i.giphy.com/media/3o6Zt2FsmthIOdUm5y/200w.webp" },
            { english: "visit", spanish: "visitar - hacer visitas", points: 3, image: "https://i.giphy.com/media/3o6ZtaDUO4wr2LJCqk/200w.webp" },
            { english: "descend", spanish: "descender - bajar", points: 3, image: "https://i.giphy.com/media/11nPtzt27joQQ8/200w.webp" },
            { english: "add", spanish: "añadir - sumar", points: 3, image: "https://i.giphy.com/media/3o6MbmXIt1qUsNzfu8/200w.webp" },
            { english: "taste", spanish: "saborear - catar - probar", points: 3, image: "https://i.giphy.com/media/l2Sq0ogljPAubE2nS/200w.webp" },
            { english: "ski", spanish: "esquiar", points: 3, image: "https://i.giphy.com/media/l0HlUVUnpHH36zoek/200w.webp" },
            { english: "flee", spanish: "evitar - huir de", points: 3, image: "https://i.giphy.com/media/S3PjeN6iPYyxJYvdji/200w.webp" },
            { english: "look", spanish: "mirar - fijar mirada en algo", points: 3, image: "https://i.giphy.com/media/kd9BlRovbPOykLBMqX/200w.webp" },
            { english: "shout", spanish: "gritar", points: 3, image: "https://i.giphy.com/media/IVT4vN0Ywp93aeKSzd/200w.webp" },
            { english: "decide", spanish: "decidir", points: 3, image: "https://i.giphy.com/media/xUA7aUNw61j9Vdzs0U/200w.webp" },
            { english: "disagree", spanish: "discrepar - no estar de acuerdo", points: 3, image: "https://i.giphy.com/media/l0HlFq5c61LraxYaI/200w.webp" },
            { english: "pack", spanish: "empacar - envasar", points: 3, image: "https://i.giphy.com/media/M8vBiv9mgpHDGpqL9y/200w.webp" },
            { english: "seem", spanish: "parecer", points: 3, image: "https://i.giphy.com/media/rVeJCzA8bCQUk4JQ4v/200w.webp" },
            { english: "offer", spanish: "ofrecer", points: 3, image: "https://i.giphy.com/media/l2QEdZMha3XrvypMY/200w.webp" },
            { english: "circle", spanish: "rodear - hacer un circulo", points: 3, image: "https://i.giphy.com/media/OtP2Jj6IuVbhu/200w.webp" },
            { english: "climb", spanish: "subir - trepar - escalar", points: 3, image: "https://i.giphy.com/media/kfLIA5rPSEdYrGvWLw/200w.webp" },
            { english: "play", spanish: "jugar - tocar - reproducir", points: 3, image: "https://i.giphy.com/media/YgsGYbakNrZg3sVmop/200w.webp" },
            { english: "vanish", spanish: "desvanecer(se) - desaparecer", points: 3, image: "https://i.giphy.com/media/kelU5SPX69mnvlKts2/200w.webp" },
            { english: "destroy", spanish: "destruir", points: 3, image: "https://i.giphy.com/media/10UHehEC098kAE/200w.webp" },
            { english: "squeeze", spanish: "apretar", points: 3, image: "https://i.giphy.com/media/TLIed7IwyosvDnXZLD/200w.webp" },
            { english: "grate", spanish: "rallar - raspar", points: 3, image: "https://i.giphy.com/media/co4PLMN4BYHdC4ZPuW/200w.webp" },
            { english: "cool", spanish: "enfriar - refrescar(se) -  calmar(se)", points: 3, image: "https://i.giphy.com/media/mGK0QLlJtLkzIx43PI/200w.webp" },
            { english: "spoil", spanish: "estropear - echar a perder - mimar", points: 3, image: "https://i.giphy.com/media/9mEPFPEwBA0JlDvYlQ/200w.webp" },
            { english: "carry", spanish: "llevar", points: 3, image: "https://i.giphy.com/media/dXA0rJGesbvFHn3RkP/200w.webp" },
            { english: "dream", spanish: "soñar", points: 3, image: "https://i.giphy.com/media/3o8doTrOWoQMV8h74k/200w.webp" },
            { english: "work", spanish: "trabajar - funcionar", points: 3, image: "https://i.giphy.com/media/13rQ7rrTrvZXlm/200w.webp" },
            { english: "punish", spanish: "castigar", points: 3, image: "https://i.giphy.com/media/pRotk2UQTsozm/200w.webp" },
            { english: "paint", spanish: "pintar", points: 3, image: "https://i.giphy.com/media/hQu3aAkP2I0bn3k1hl/200w.webp" },
            { english: "talk", spanish: "hablar - conversar", points: 3, image: "https://i.giphy.com/media/M8xmO5ZcLPtAY/200w.webp" },
            { english: "peel", spanish: "pelar", points: 3, image: "https://i.giphy.com/media/p3P5xLjTI2iu13ronY/200w.webp" },
            { english: "underline", spanish: "subrayar", points: 3, image: "https://i.giphy.com/media/KBDGEAI1JHIftkUhjD/200w.webp" },
            { english: "discover", spanish: "descubrir", points: 3, image: "https://i.giphy.com/media/0IGsC1JY4k0LzdDJfb/200w.webp" },
            { english: "check", spanish: "comprobar -  chequear -  verificar", points: 3, image: "https://i.giphy.com/media/kLOkqcrdC5mrCE7k7G/200w.webp" },
            { english: "stay", spanish: "permanecer - quedarse - durar", points: 3, image: "https://i.giphy.com/media/TGUIq0O5s4XJSnefJ3/200w.webp" },
            { english: "cheer", spanish: "victorear -  alegrar -  animar -  aplaudir", points: 3, image: "https://i.giphy.com/media/11sBLVxNs7v6WA/200w.webp" },
            { english: "speed", spanish: "acelerar - apresurarse - darse prisa", points: 3, image: "https://i.giphy.com/media/qxM03tz9rg4RYThmkG/200w.webp" },
            { english: "count", spanish: "contar", points: 3, image: "https://i.giphy.com/media/xUPGcqaVH1cDeKZTBS/200w.webp" },
        ]
    },
    {
        name: "2. Verbos Regulares",
        icon: "🧗‍♀️",
        words: [
            { english: "pack", spanish: "empaquetar", points: 3 },
            { english: "watch", spanish: "vigilar", points: 3 },
            { english: "check", spanish: "comprobar", points: 3 },
            { english: "explode", spanish: "estallar", points: 3 },
            { english: "deliver", spanish: "entregar", points: 3 },
            { english: "adorn", spanish: "adornar", points: 3 },
            { english: "suffer", spanish: "sufrir", points: 3 },
            { english: "repair", spanish: "reparar", points: 3 },
            { english: "love", spanish: "amar", points: 3 },
            { english: "remind", spanish: "recordar", points: 3 },
            { english: "accede", spanish: "acceder", points: 3 },
            { english: "earn", spanish: "ganar", points: 3 },
            { english: "fail", spanish: "fallar", points: 3 },
            { english: "attract", spanish: "atraer", points: 3 },
            { english: "return", spanish: "volver", points: 3 },
            { english: "abandon", spanish: "abandonar", points: 3 },
            { english: "beg", spanish: "rogar, pedir", points: 3 },
            { english: "sign", spanish: "firmar", points: 3 },
            { english: "happen", spanish: "suceder", points: 3 },
            { english: "suggest", spanish: "sugerir", points: 3 },
            { english: "advise", spanish: "aconsejar", points: 3 },
            { english: "hang", spanish: "ahorcar", points: 3 },
            { english: "smoke", spanish: "fumar", points: 3 },
            { english: "thank", spanish: "agradecer", points: 3 },
            { english: "hire", spanish: "alquilar", points: 3 },
            { english: "invent", spanish: "inventar", points: 3 },
            { english: "start", spanish: "empezar", points: 3 },
            { english: "disturb", spanish: "perturbar", points: 3 },
            { english: "arrive", spanish: "llegar", points: 3 },
            { english: "pull", spanish: "tirar de", points: 3 },
            { english: "inquire", spanish: "averiguar", points: 3 },
            { english: "arrange", spanish: "arreglar", points: 3 },
            { english: "name", spanish: "nombrar", points: 3 },
            { english: "climb", spanish: "trepar", points: 3 },
            { english: "shout", spanish: "gritar", points: 3 },
            { english: "fix", spanish: "fijar", points: 3 },
            { english: "call", spanish: "llamar", points: 3 },
            { english: "impress", spanish: "impresionar", points: 3 },
            { english: "fold", spanish: "doblar", points: 3 },
            { english: "receive", spanish: "recibir", points: 3 },
            { english: "follow", spanish: "seguir", points: 3 },
            { english: "collect", spanish: "recoger", points: 3 },
            { english: "tame", spanish: "domesticar", points: 3 },
            { english: "assure", spanish: "asegurar", points: 3 },
            { english: "tire", spanish: "cansar", points: 3 },
            { english: "advertise", spanish: "anunciar", points: 3 },
            { english: "remain", spanish: "permanecer", points: 3 },
            { english: "like", spanish: "gustar", points: 3 },
            { english: "admit", spanish: "admitir", points: 3 },
            { english: "decide", spanish: "decidir", points: 3 }
        ]
    },
    {
        name: "3. Verbos Regulares",
        icon: "🏊‍♀️",
        words: [
            { english: "book", spanish: "reservar", points: 3 },
            { english: "rent", spanish: "arrendar", points: 3 },
            { english: "ask", spanish: "preguntar", points: 3 },
            { english: "bathe", spanish: "bañarse", points: 3 },
            { english: "abuse", spanish: "injuriar", points: 3 },
            { english: "look", spanish: "mirar", points: 3 },
            { english: "rest", spanish: "descansar", points: 3 },
            { english: "last", spanish: "durar", points: 3 },
            { english: "taste", spanish: "probar", points: 3 },
            { english: "blame", spanish: "culpar", points: 3 },
            { english: "gain", spanish: "ganar", points: 3 },
            { english: "employ", spanish: "emplear", points: 3 },
            { english: "sharpen", spanish: "afilar", points: 3 },
            { english: "walk", spanish: "andar", points: 3 },
            { english: "visit", spanish: "visitar", points: 3 },
            { english: "joke", spanish: "bromear", points: 3 },
            { english: "float", spanish: "flotar", points: 3 },
            { english: "fill", spanish: "llenar", points: 3 },
            { english: "handle", spanish: "manejar", points: 3 },
            { english: "notice", spanish: "notar, darse cuenta", points: 3 },
            { english: "finish", spanish: "acabar", points: 3 },
            { english: "suppose", spanish: "suponer", points: 3 },
            { english: "cover", spanish: "cubrir", points: 3 },
            { english: "divide", spanish: "dividir", points: 3 },
            { english: "pass", spanish: "pasar", points: 3 },
            { english: "achieve", spanish: "llevar a cabo", points: 3 },
            { english: "claim", spanish: "reclamar", points: 3 },
            { english: "lower", spanish: "bajar", points: 3 },
            { english: "order", spanish: "ordenar", points: 3 },
            { english: "require", spanish: "requerir", points: 3 },
            { english: "produce", spanish: "producir", points: 3 },
            { english: "adore", spanish: "adorar", points: 3 },
            { english: "deceive", spanish: "engañar", points: 3 },
            { english: "absorb", spanish: "absorber", points: 3 },
            { english: "note", spanish: "notar", points: 3 },
            { english: "kill", spanish: "matar", points: 3 },
            { english: "talk", spanish: "hablar", points: 3 },
            { english: "import", spanish: "importar", points: 3 },
            { english: "conceal", spanish: "ocultar", points: 3 },
            { english: "vary", spanish: "variar", points: 3 },
            { english: "defend", spanish: "defender", points: 3 },
            { english: "hope", spanish: "esperar", points: 3 },
            { english: "surprise", spanish: "sorprender", points: 3 },
            { english: "declare", spanish: "declarar", points: 3 },
            { english: "elect", spanish: "elegir", points: 3 },
            { english: "laugh", spanish: "reír", points: 3 },
            { english: "accent", spanish: "acentuar", points: 3 },
            { english: "trouble", spanish: "molestar", points: 3 },
            { english: "express", spanish: "expresar", points: 3 },
            { english: "try", spanish: "probar", points: 3 }
        ]
    },
    {
        name: "4. Verbos Regulares",
        icon: "🧑‍🎨",
        words: [
            { english: "relieve", spanish: "aliviar", points: 3 },
            { english: "oblige", spanish: "obligar", points: 3 },
            { english: "commit", spanish: "cometer", points: 3 },
            { english: "close", spanish: "cerrar", points: 3 },
            { english: "mention", spanish: "mencionar", points: 3 },
            { english: "believe", spanish: "creer", points: 3 },
            { english: "refer", spanish: "referir", points: 3 },
            { english: "seem", spanish: "parecer", points: 3 },
            { english: "open", spanish: "abrir", points: 3 },
            { english: "weigh", spanish: "pesar", points: 3 },
            { english: "smile", spanish: "sonreír", points: 3 },
            { english: "clean", spanish: "limpiar", points: 3 },
            { english: "acquire", spanish: "adquirir", points: 3 },
            { english: "number", spanish: "numerar", points: 3 },
            { english: "permit", spanish: "permitir", points: 3 },
            { english: "worry", spanish: "preocuparse", points: 3 },
            { english: "please", spanish: "agradar", points: 3 },
            { english: "refuse", spanish: "rehusar", points: 3 },
            { english: "crown", spanish: "coronar", points: 3 },
            { english: "play", spanish: "jugar", points: 3 },
            { english: "include", spanish: "incluir", points: 3 },
            { english: "command", spanish: "mandar", points: 3 },
            { english: "marry", spanish: "casarse", points: 3 },
            { english: "cash", spanish: "cobrar", points: 3 },
            { english: "establish", spanish: "establecer", points: 3 },
            { english: "fish", spanish: "pescar", points: 3 },
            { english: "remove", spanish: "quitar", points: 3 },
            { english: "reach", spanish: "alcanzar", points: 3 },
            { english: "trust", spanish: "confiar", points: 3 },
            { english: "report", spanish: "informar", points: 3 },
            { english: "cross", spanish: "cruzar", points: 3 },
            { english: "fear", spanish: "temer", points: 3 },
            { english: "kiss", spanish: "besar", points: 3 },
            { english: "cease", spanish: "cesar", points: 3 },
            { english: "save", spanish: "ahorrar", points: 3 },
            { english: "use", spanish: "usar", points: 3 },
            { english: "answer", spanish: "contestar", points: 3 },
            { english: "agree", spanish: "acceder", points: 3 },
            { english: "accuse", spanish: "acusar", points: 3 },
            { english: "hate", spanish: "odiar", points: 3 },
            { english: "continue", spanish: "continuar", points: 3 },
            { english: "invite", spanish: "invitar", points: 3 },
            { english: "amount", spanish: "ascender/cantidad", points: 3 },
            { english: "allow", spanish: "permitir", points: 3 },
            { english: "copy", spanish: "copiar", points: 3 },
            { english: "intend", spanish: "proponerse", points: 3 },
            { english: "act", spanish: "actuar", points: 3 },
            { english: "help", spanish: "ayudar", points: 3 },
            { english: "touch", spanish: "tocar", points: 3 },
            { english: "greet", spanish: "saludar", points: 3 }
        ]
    },
    {
        name: "5. Verbos Regulares",
        icon: "🏇",
        words: [
            { english: "justify", spanish: "justificar", points: 3 },
            { english: "dry", spanish: "secar", points: 3 },
            { english: "listen", spanish: "escuchar", points: 3 },
            { english: "advance", spanish: "avanzar", points: 3 },
            { english: "correct", spanish: "corregir", points: 3 },
            { english: "enjoy", spanish: "disfrutar", points: 3 },
            { english: "prepare", spanish: "preparar", points: 3 },
            { english: "esteem", spanish: "estimar", points: 3 },
            { english: "detach", spanish: "separar", points: 3 },
            { english: "annoy", spanish: "molestar", points: 3 },
            { english: "want", spanish: "querer", points: 3 },
            { english: "expect", spanish: "esperar", points: 3 },
            { english: "consist", spanish: "consistir", points: 3 },
            { english: "test", spanish: "probar", points: 3 },
            { english: "absolve", spanish: "absolver", points: 3 },
            { english: "appear", spanish: "aparecer", points: 3 },
            { english: "fetch", spanish: "ir por", points: 3 },
            { english: "guard", spanish: "guardar", points: 3 },
            { english: "wait", spanish: "esperar", points: 3 },
            { english: "contain", spanish: "contener", points: 3 },
            { english: "live", spanish: "vivir", points: 3 },
            { english: "possess", spanish: "poseer", points: 3 },
            { english: "consider", spanish: "considerar", points: 3 },
            { english: "obey", spanish: "obedecer", points: 3 },
            { english: "compose", spanish: "componer", points: 3 },
            { english: "dawn", spanish: "amanecer", points: 3 },
            { english: "attend", spanish: "asistir", points: 3 },
            { english: "wish", spanish: "desear", points: 3 },
            { english: "apologize", spanish: "excusarse", points: 3 },
            { english: "attack", spanish: "atacar", points: 3 },
            { english: "amuse", spanish: "divertir", points: 3 },
            { english: "rain", spanish: "llover", points: 3 },
            { english: "iron", spanish: "planchar", points: 3 },
            { english: "join", spanish: "unir", points: 3 },
            { english: "clear", spanish: "aclarar, limpiar", points: 3 },
            { english: "despise", spanish: "despreciar", points: 3 },
            { english: "sound", spanish: "sonar", points: 3 },
            { english: "damage", spanish: "dañar", points: 3 },
            { english: "kick", spanish: "cocear", points: 3 },
            { english: "stop", spanish: "parar", points: 3 },
            { english: "appoint", spanish: "nombrar", points: 3 },
            { english: "devote", spanish: "dedicar", points: 3 },
            { english: "move", spanish: "mover", points: 3 },
            { english: "reply", spanish: "replicar", points: 3 },
            { english: "drop", spanish: "dejar caer", points: 3 },
            { english: "change", spanish: "cambiar", points: 3 },
            { english: "enclose", spanish: "incluir", points: 3 },
            { english: "guess", spanish: "adivinar", points: 3 },
            { english: "lie", spanish: "mentir", points: 3 },
            { english: "wash", spanish: "lavar", points: 3 }
        ]
    },
    {
        name: "6. Verbos Regulares",
        icon: "🧑‍🍳",
        words: [
            { english: "tie", spanish: "atar", points: 3 },
            { english: "admire", spanish: "admirar", points: 3 },
            { english: "promise", spanish: "prometer", points: 3 },
            { english: "gather", spanish: "recoger", points: 3 },
            { english: "extract", spanish: "extraer", points: 3 },
            { english: "attempt", spanish: "intentar", points: 3 },
            { english: "improve", spanish: "mejorar", points: 3 },
            { english: "offer", spanish: "ofrecer", points: 3 },
            { english: "evoke", spanish: "evocar", points: 3 },
            { english: "remember", spanish: "recordar", points: 3 },
            { english: "belong", spanish: "pertenecer", points: 3 },
            { english: "mend", spanish: "componer", points: 3 },
            { english: "discover", spanish: "descubrir", points: 3 },
            { english: "avoid", spanish: "evitar", points: 3 },
            { english: "encourage", spanish: "animar", points: 3 },
            { english: "hurry", spanish: "apresurarse", points: 3 },
            { english: "gamble", spanish: "jugar", points: 3 },
            { english: "desire", spanish: "desear", points: 3 },
            { english: "request", spanish: "suplicar, requerir", points: 3 },
            { english: "found", spanish: "fundar", points: 3 },
            { english: "accelerate", spanish: "acelerar", points: 3 },
            { english: "announce", spanish: "anunciar", points: 3 },
            { english: "govern", spanish: "gobernar", points: 3 },
            { english: "organize", spanish: "organizar", points: 3 },
            { english: "drag", spanish: "arrastrar", points: 3 },
            { english: "add", spanish: "sumar", points: 3 },
            { english: "dislike", spanish: "desaprobar", points: 3 },
            { english: "study", spanish: "estudiar", points: 3 },
            { english: "prefer", spanish: "preferir", points: 3 },
            { english: "wound", spanish: "herir", points: 3 },
            { english: "approve", spanish: "aprobar", points: 3 },
            { english: "count", spanish: "contar", points: 3 },
            { english: "affirm", spanish: "afirmar", points: 3 },
            { english: "destroy", spanish: "destruir", points: 3 }
        ]
    },
]




export const seedData = {
    lists
}