import { IList } from "../interface"


const lists: IList[] = [
    {
        name: "1. Verbos Regulares",
        icon: "⛹️",
        words: [
            { english: "divide", spanish: "dividir", points: 0, image: " https://i.giphy.com/media/6PDD11h741IpG/200w.webp" },
            { english: "support", spanish: "soportar", points: 0, image: " https://i.giphy.com/media/ew8hN0QnkoaOdTn2Eo/200w.webp" },
            { english: "follow", spanish: "seguir", points: 0, image: " https://i.giphy.com/media/TisFptjsMKzYp1fAzo/200w.webp" },
            { english: "complete", spanish: "completar", points: 0, image: " https://i.giphy.com/media/Q5RiiXiUWWVjvE3rER/200w.webp" },
            { english: "suck", spanish: "chupar", points: 0, image: " https://i.giphy.com/media/FnxHqXpcyYN32/200w.webp" },
            { english: "pull", spanish: "halar - tirar de", points: 0, image: " https://i.giphy.com/media/SsIZAm4IDC6yUQMa45/200w.webp" },
            { english: "practice", spanish: "practicar", points: 0, image: " https://i.giphy.com/media/xT9DPjkNXsQuoZva6c/200w.webp" },
            { english: "lower", spanish: "bajar - reducir - disminuir", points: 0, image: " https://i.giphy.com/media/g8tLOZ6RWlDvRf5Kfp/200w.webp" },
            { english: "kiss", spanish: "besar", points: 0, image: " https://i.giphy.com/media/l2Je2M4Nfrit0L7sQ/200w.webp" },
            { english: "wed", spanish: "casar(se) - unirse con", points: 0, image: " https://i.giphy.com/media/urgh3QkW9wgG8goYCQ/200w.webp" },
            { english: "smile", spanish: "sonreir", points: 0, image: " https://i.giphy.com/media/QTrG6mjkHEkpFR3DqX/200w.webp" },
            { english: "fish", spanish: "pescar", points: 0, image: " https://i.giphy.com/media/Xy0VPXTENJyG2HFqtr/200w.webp" },
            { english: "rest", spanish: "descansar - reposar", points: 0, image: " https://i.giphy.com/media/fdlcvptCs4qsM/200w.webp" },
            { english: "warm", spanish: "calentar(se) - recalentar", points: 0, image: " https://i.giphy.com/media/3o6Zt2FsmthIOdUm5y/200w.webp" },
            { english: "visit", spanish: "visitar - hacer visitas", points: 0, image: " https://i.giphy.com/media/3o6ZtaDUO4wr2LJCqk/200w.webp" },
            { english: "descend", spanish: "descender - bajar", points: 0, image: " https://i.giphy.com/media/11nPtzt27joQQ8/200w.webp" },
            { english: "add", spanish: "añadir - sumar", points: 0, image: " https://i.giphy.com/media/3o6MbmXIt1qUsNzfu8/200w.webp" },
            { english: "taste", spanish: "saborear - catar - probar", points: 0, image: " https://i.giphy.com/media/l2Sq0ogljPAubE2nS/200w.webp" },
            { english: "ski", spanish: "esquiar", points: 0, image: " https://i.giphy.com/media/l0HlUVUnpHH36zoek/200w.webp" },
            { english: "flee", spanish: "evitar - huir de", points: 0, image: " https://i.giphy.com/media/S3PjeN6iPYyxJYvdji/200w.webp" },
            { english: "look", spanish: "mirar - fijar mirada en algo", points: 0, image: " https://i.giphy.com/media/kd9BlRovbPOykLBMqX/200w.webp" },
            { english: "shout", spanish: "gritar", points: 0, image: " https://i.giphy.com/media/IVT4vN0Ywp93aeKSzd/200w.webp" },
            { english: "decide", spanish: "decidir", points: 0, image: " https://i.giphy.com/media/xUA7aUNw61j9Vdzs0U/200w.webp" },
            { english: "disagree", spanish: "discrepar - no estar de acuerdo", points: 0, image: " https://i.giphy.com/media/l0HlFq5c61LraxYaI/200w.webp" },
            { english: "pack", spanish: "empacar - envasar", points: 0, image: " https://i.giphy.com/media/M8vBiv9mgpHDGpqL9y/200w.webp" },
            { english: "seem", spanish: "parecer", points: 0, image: " https://i.giphy.com/media/rVeJCzA8bCQUk4JQ4v/200w.webp" },
            { english: "offer", spanish: "ofrecer", points: 0, image: " https://i.giphy.com/media/l2QEdZMha3XrvypMY/200w.webp" },
            { english: "circle", spanish: "rodear - hacer un circulo", points: 0, image: " https://i.giphy.com/media/OtP2Jj6IuVbhu/200w.webp" },
            { english: "climb", spanish: "subir - trepar - escalar", points: 0, image: " https://i.giphy.com/media/kfLIA5rPSEdYrGvWLw/200w.webp" },
            { english: "play", spanish: "jugar - tocar - reproducir", points: 0, image: " https://i.giphy.com/media/YgsGYbakNrZg3sVmop/200w.webp" },
            { english: "vanish", spanish: "desvanecer(se) - desaparecer", points: 0, image: " https://i.giphy.com/media/kelU5SPX69mnvlKts2/200w.webp" },
            { english: "destroy", spanish: "destruir", points: 0, image: " https://i.giphy.com/media/10UHehEC098kAE/200w.webp" },
            { english: "squeeze", spanish: "apretar", points: 0, image: " https://i.giphy.com/media/TLIed7IwyosvDnXZLD/200w.webp" },
            { english: "grate", spanish: "rallar - raspar", points: 0, image: " https://i.giphy.com/media/co4PLMN4BYHdC4ZPuW/200w.webp" },
            { english: "cool", spanish: "enfriar - refrescar(se) -  calmar(se)", points: 0, image: " https://i.giphy.com/media/mGK0QLlJtLkzIx43PI/200w.webp" },
            { english: "spoil", spanish: "estropear - echar a perder - mimar", points: 0, image: " https://i.giphy.com/media/9mEPFPEwBA0JlDvYlQ/200w.webp" },
            { english: "carry", spanish: "llevar", points: 0, image: " https://i.giphy.com/media/dXA0rJGesbvFHn3RkP/200w.webp" },
            { english: "dream", spanish: "soñar", points: 0, image: " https://i.giphy.com/media/3o8doTrOWoQMV8h74k/200w.webp" },
            { english: "work", spanish: "trabajar - funcionar", points: 0, image: " https://i.giphy.com/media/13rQ7rrTrvZXlm/200w.webp" },
            { english: "punish", spanish: "castigar", points: 0, image: " https://i.giphy.com/media/pRotk2UQTsozm/200w.webp" },
            { english: "paint", spanish: "pintar", points: 0, image: " https://i.giphy.com/media/hQu3aAkP2I0bn3k1hl/200w.webp" },
            { english: "talk", spanish: "hablar - conversar", points: 0, image: " https://i.giphy.com/media/M8xmO5ZcLPtAY/200w.webp" },
            { english: "peel", spanish: "pelar", points: 0, image: " https://i.giphy.com/media/p3P5xLjTI2iu13ronY/200w.webp" },
            { english: "underline", spanish: "subrayar", points: 0, image: " https://i.giphy.com/media/KBDGEAI1JHIftkUhjD/200w.webp" },
            { english: "discover", spanish: "descubrir", points: 0, image: " https://i.giphy.com/media/0IGsC1JY4k0LzdDJfb/200w.webp" },
            { english: "check", spanish: "comprobar -  chequear -  verificar", points: 0, image: " https://i.giphy.com/media/kLOkqcrdC5mrCE7k7G/200w.webp" },
            { english: "stay", spanish: "permanecer - quedarse - durar", points: 0, image: " https://i.giphy.com/media/TGUIq0O5s4XJSnefJ3/200w.webp" },
            { english: "cheer", spanish: "victorear -  alegrar -  animar -  aplaudir", points: 0, image: " https://i.giphy.com/media/11sBLVxNs7v6WA/200w.webp" },
            { english: "speed", spanish: "acelerar - apresurarse - darse prisa", points: 0, image: " https://i.giphy.com/media/qxM03tz9rg4RYThmkG/200w.webp" },
            { english: "count", spanish: "contar", points: 0, image: " https://i.giphy.com/media/xUPGcqaVH1cDeKZTBS/200w.webp" },
        ]
    },
    {
        name: "2. Verbos Regulares",
        icon: "🎶",
        words: [
            { english: "laugh", spanish: "reir(se)", points: 0, image: " https://i.giphy.com/media/CoDp6NnSmItoY/200w.webp" },
            { english: "mop", spanish: "trapear - fregar", points: 0, image: " https://i.giphy.com/media/l2YWkhCvZ2ufDVar6/200w.webp" },
            { english: "cancel", spanish: "cancelar", points: 0, image: " https://i.giphy.com/media/l4FGlqf3GnH6mXY08/200w.webp" },
            { english: "pronounce", spanish: "pronunciar", points: 0, image: " https://i.giphy.com/media/l2JdZtmjxPJ2M1d9C/200w.webp" },
            { english: "describe", spanish: "describir", points: 0, image: " https://i.giphy.com/media/STLj8QUhg25pe/200w.webp" },
            { english: "listen to", spanish: "escuchar", points: 0, image: " https://i.giphy.com/media/4oMoIbIQrvCjm/200w.webp" },
            { english: "fill", spanish: "llenar - rellenar", points: 0, image: " https://i.giphy.com/media/xT9IgFQsNYi1zBUiyc/200w.webp" },
            { english: "discuss", spanish: "discutir", points: 0, image: " https://i.giphy.com/media/kSacoMuLSoNTfInwsB/200w.webp" },
            { english: "splash", spanish: "salpicar - rociar", points: 0, image: " https://i.giphy.com/media/iNZffK78WQ0LF3ZWLb/200w.webp" },
            { english: "inspect", spanish: "inspeccionar", points: 0, image: " https://i.giphy.com/media/jFhWlcjuUkEacx4ZCU/200w.webp" },
            { english: "help", spanish: "ayudar - socorrer", points: 0, image: " https://i.giphy.com/media/l0Extn1wgzXyZn0J2/200w.webp" },
            { english: "order", spanish: "ordenar - disponer", points: 0, image: " https://i.giphy.com/media/03xd6iUVUOSgSMupzO/200w.webp" },
            { english: "assign", spanish: "asignar", points: 0, image: " https://i.giphy.com/media/l2SpQlNVrKuypajWE/200w.webp" },
            { english: "plan", spanish: "planear", points: 0, image: " https://i.giphy.com/media/yv1ggi3Cbase05a8iS/200w.webp" },
            { english: "move", spanish: "mover - trastear", points: 0, image: " https://i.giphy.com/media/3F1pInHV8vz5HXfAzM/200w.webp" },
            { english: "remember", spanish: "recordar -  acordarse", points: 0, image: " https://i.giphy.com/media/3orieTQUh6WCMckclq/200w.webp" },
            { english: "wait", spanish: "esperar", points: 0, image: " https://i.giphy.com/media/l0HlBO7eyXzSZkJri/200w.webp" },
            { english: "enjoy", spanish: "gozar(de) - disfrutar disfrutar", points: 0, image: " https://i.giphy.com/media/ifM0rVliHWXfsEEQOS/200w.webp" },
            { english: "believe", spanish: "creer", points: 0, image: " https://i.giphy.com/media/3o6wrGqTd5HbwPJkYw/200w.webp" },
            { english: "share", spanish: "compartir", points: 0, image: " https://i.giphy.com/media/1oFqxMYv5JQvuFtX8o/200w.webp" },
            { english: "watch", spanish: "observar - velar - vigilar", points: 0, image: " https://i.giphy.com/media/n6Gk6pAMeP9NS/200w.webp" },
            { english: "lead", spanish: "conducir - liderar", points: 0, image: " https://i.giphy.com/media/3orif4BtRvTgRedJF6/200w.webp" },
            { english: "wash", spanish: "lavar - fregar - mojar", points: 0, image: " https://i.giphy.com/media/oM8CvBlVubezC/200w.webp" },
            { english: "calm", spanish: "calmar", points: 0, image: " https://i.giphy.com/media/2ilegKh8fMdJAVqbG2/200w.webp" },
            { english: "copy", spanish: "copiar", points: 0, image: " https://i.giphy.com/media/FZPBHxQbXbOUUB69Q7/200w.webp" },
            { english: "attach", spanish: "unir - juntar - sujetar - pegar", points: 0, image: " https://i.giphy.com/media/Y1dzeiMAHY3ohSFPZC/200w.webp" },
            { english: "worry", spanish: "preocupar", points: 0, image: " https://i.giphy.com/media/14oABfwMhnvZfi/200w.webp" },
            { english: "award", spanish: "otorgar", points: 0, image: " https://i.giphy.com/media/CMVMPGhA7yHdYxo7Xf/200w.webp" },
            { english: "like", spanish: "gustar - querer", points: 0, image: " https://i.giphy.com/media/l0IyccEqUTO7xy9Ec/200w.webp" },
            { english: "dance", spanish: "bailar", points: 0, image: " https://i.giphy.com/media/EFgksQHxImgta/200w.webp" },
            { english: "excuse", spanish: "excusar", points: 0, image: " https://i.giphy.com/media/SY44A3CMBwM83yI7t2/200w.webp" },
            { english: "place", spanish: "poner - colocar - situar", points: 0, image: " https://i.giphy.com/media/hSjSZkQtCHdAbgEZPc/200w.webp" },
            { english: "sprinkle", spanish: "rociar", points: 0, image: " https://i.giphy.com/media/l4Jz3a8jO92crUlWM/200w.webp" },
            { english: "celebrate", spanish: "celebrar", points: 0, image: " https://i.giphy.com/media/jcwDyr6UBjLebH863a/200w.webp" },
            { english: "assist", spanish: "asistir - ayudar ", points: 0, image: " https://i.giphy.com/media/kD4pknHevDUQNOTSbl/200w.webp" },
            { english: "mix", spanish: "mezclar - barajar", points: 0, image: " https://i.giphy.com/media/1X7qz2KCFnU0Il8RSk/200w.webp" },
            { english: "defend", spanish: "defender", points: 0, image: " https://i.giphy.com/media/nG9tIH9H7CAk9sEDfu/200w.webp" },
            { english: "sharpen", spanish: "afilar - ampliar", points: 0, image: " https://i.giphy.com/media/7SoghL1WjxTK9CkkpS/200w.webp" },
            { english: "blush", spanish: "sonrojar", points: 0, image: " https://i.giphy.com/media/rpf0Du8NasK6Q/200w.webp" },
            { english: "attend", spanish: "atender", points: 0, image: " https://i.giphy.com/media/6MpYHxuYBaRcD9eF4L/200w.webp" },
            { english: "type", spanish: "mecanografiar - digitar", points: 0, image: " https://i.giphy.com/media/3o7aCTfyhYawdOXcFW/200w.webp" },
            { english: "clap", spanish: "aplaudir", points: 0, image: " https://i.giphy.com/media/1236TCtX5dsGEo/200w.webp" },
            { english: "fade", spanish: "desteñir - desvanecer(se)", points: 0, image: " https://i.giphy.com/media/d8P7zL3QrEotHWPRrR/200w.webp" },
            { english: "learn", spanish: "aprender", points: 0, image: " https://i.giphy.com/media/qKltgF7Aw515K/200w.webp" },
            { english: "chill", spanish: "resfriar", points: 0, image: " https://i.giphy.com/media/5hxsG54XihuvDNsrCB/200w.webp" },
            { english: "open", spanish: "abrir", points: 0, image: " https://i.giphy.com/media/jyPWfqzhit2HEBDymN/200w.webp" },
            { english: "prefer", spanish: "preferir", points: 0, image: " https://i.giphy.com/media/HrFiaDpS7mP1XzJiZZ/200w.webp" },
            { english: "use", spanish: "usar", points: 0, image: " https://i.giphy.com/media/mgJHCuKiCy5KU/200w.webp" },
            { english: "notice", spanish: "notar - advertir", points: 0, image: " https://i.giphy.com/media/VPevIZhmlNOms/200w.webp" },
            { english: "jog", spanish: "trotar", points: 0, image: " https://i.giphy.com/media/CXLdpFUp9zsoaw3X8c/200w.webp" },
        ]
    },
    {
        name: "3. Verbos Regulares",
        icon: "🏊",
        words: [
            { english: "grade", spanish: "graduar - calificar - clasificar", points: 0, image: " https://i.giphy.com/media/iH1rdIKYvNhOu5Z8RY/200w.webp" },
            { english: "demostrate", spanish: "demostrar", points: 0, image: " https://i.giphy.com/media/l1Kdb3gWBSzFgVIek/200w.webp" },
            { english: "enroll", spanish: "inscribirse - matricular", points: 0, image: " https://i.giphy.com/media/oyGpShr0FL7Fmdu1CG/200w.webp" },
            { english: "stop", spanish: "parar - detener", points: 0, image: " https://i.giphy.com/media/l4FGDLkDkCnsKwdnq/200w.webp" },
            { english: "ask", spanish: "preguntar", points: 0, image: " https://i.giphy.com/media/3o6ozoD1ByqYv7ARIk/200w.webp" },
            { english: "turn", spanish: "girar - dar vueltas -  dar la vuelta", points: 0, image: " https://i.giphy.com/media/ohMtDzrhrWgnK/200w.webp" },
            { english: "weigh", spanish: "pesar", points: 0, image: " https://i.giphy.com/media/FlOHnTIv1mj2U/200w.webp" },
            { english: "boil", spanish: "hervir", points: 0, image: " https://i.giphy.com/media/6qhETmXwBIogg/200w.webp" },
            { english: "remain", spanish: "permanecer - quedarse", points: 0, image: " https://i.giphy.com/media/XEo7YJHUeplXa/200w.webp" },
            { english: "sigh", spanish: "suspirar - susurrar", points: 0, image: " https://i.giphy.com/media/UUcVHqcMwWMcUoNmSN/200w.webp" },
            { english: "vacuum", spanish: "aspirar", points: 0, image: " https://i.giphy.com/media/cSw9SQuGRjvr2/200w.webp" },
            { english: "mind", spanish: "agregar - importar - preocuparse", points: 0, image: " https://i.giphy.com/media/ZCqUyl4FbVYqO3xZBW/200w.webp" },
            { english: "happen", spanish: "suceder - ocurrir - pasar", points: 0, image: " https://i.giphy.com/media/1lxT4sT6Grek6Ma6mW/200w.webp" },
            { english: "cry", spanish: "llorar - gritar", points: 0, image: " https://i.giphy.com/media/3o6wrvdHFbwBrUFenu/200w.webp" },
            { english: "imitate", spanish: "imitar", points: 0, image: " https://i.giphy.com/media/3orifcQSbDdACie0Y8/200w.webp" },
            { english: "answer", spanish: "contestar - responder", points: 0, image: " https://i.giphy.com/media/3o7aD8WTuPv088JAsg/200w.webp" },
            { english: "wish", spanish: "desear", points: 0, image: " https://i.giphy.com/media/tpTOw6sljB2U/200w.webp" },
            { english: "mislay", spanish: "extraviar - perder", points: 0, image: " https://i.giphy.com/media/l41lFw057lAJQMwg0/200w.webp" },
            { english: "bake", spanish: "hornear", points: 0, image: " https://i.giphy.com/media/EQNWSCCJDIGP8U77c7/200w.webp" },
            { english: "study", spanish: "estudiar", points: 0, image: " https://i.giphy.com/media/S3Pe5NZqgmE8Tl3NI5/200w.webp" },
            { english: "absorb", spanish: "absorber", points: 0, image: " https://i.giphy.com/media/3oKHWguzCf0ENuevxS/200w.webp" },
            { english: "translate", spanish: "traducir", points: 0, image: " https://i.giphy.com/media/3o6vXNQiixBMsf4Dra/200w.webp" },
            { english: "sew", spanish: "coser", points: 0, image: " https://i.giphy.com/media/8Z5H7TFRdlzIuhPKPy/200w.webp" },
            { english: "simmer", spanish: "cocer a fuego lento", points: 0, image: " https://i.giphy.com/media/nlJDPZHcLMJhlXgV1c/200w.webp" },
            { english: "advance", spanish: "avanzar", points: 0, image: " https://i.giphy.com/media/xTiN0GwG6QAh1yjzEs/200w.webp" },
            { english: "relax", spanish: "relajar - mitigar", points: 0, image: " https://i.giphy.com/media/dCG87dWyRNPEgiLQmm/200w.webp" },
            { english: "omit", spanish: "omitir", points: 0, image: " https://i.giphy.com/media/26uf2EG78j1paWycw/200w.webp" },
            { english: "spell", spanish: "deletrear", points: 0, image: " https://i.giphy.com/media/w6LzYFWvgn6RQxKH5M/200w.webp" },
            { english: "kick", spanish: "patear - dar punta piés", points: 0, image: " https://i.giphy.com/media/Ur7br2RDlMlZQzuwUK/200w.webp" },
            { english: "plant", spanish: "plantar - sembrar", points: 0, image: " https://i.giphy.com/media/4QFBn7Or4Qw43x6qVs/200w.webp" },
            { english: "repair", spanish: "reparar - arreglar", points: 0, image: " https://i.giphy.com/media/BcJbdfFSsJPwK4O66J/200w.webp" },
            { english: "empty", spanish: "vaciar", points: 0, image: " https://i.giphy.com/media/Eqz2BTIm1HWrYftdLD/200w.webp" },
            { english: "manage", spanish: "manejar - dirigir - arreglárselas", points: 0, image: " https://i.giphy.com/media/p2Ow6zI8NbaCeBnpHV/200w.webp" },
            { english: "enter", spanish: "entrar", points: 0, image: " https://i.giphy.com/media/KIUU4xdCbIA1D24jLu/200w.webp" },
            { english: "hate", spanish: "odiar - aborrecer - detestar", points: 0, image: " https://i.giphy.com/media/Ol759kRKsQPn2/200w.webp" },
            { english: "lick", spanish: "lamer - adular", points: 0, image: " https://i.giphy.com/media/iTtFV9jZbc90YLwwJj/200w.webp" },
            { english: "touch", spanish: "tocar - rozar", points: 0, image: " https://i.giphy.com/media/109RutRrTGY97a/200w.webp" },
            { english: "whistle", spanish: "silbar", points: 0, image: " https://i.giphy.com/media/9E5wP1RiPvnos/200w.webp" },
            { english: "spill", spanish: "derramar -  regar", points: 0, image: " https://i.giphy.com/media/SZQBPO4NqHkh6wmdXk/200w.webp" },
            { english: "chew", spanish: "masticar", points: 0, image: " https://i.giphy.com/media/da17TWjELQ27RpHXds/200w.webp" },
            { english: "agree", spanish: "acordar - estar de acuerdo -  acceder", points: 0, image: " https://i.giphy.com/media/jN0ygssTH2hoI/200w.webp" },
            { english: "bleed", spanish: "sangrar", points: 0, image: " https://i.giphy.com/media/QJtiS9rHFqauLNJ5cP/200w.webp" },
            { english: "charge", spanish: "cargar", points: 0, image: " https://i.giphy.com/media/MdeSslU80bVsTtWxEh/200w.webp" },
            { english: "decorate", spanish: "decorar", points: 0, image: " https://i.giphy.com/media/3HBTLptQKeJ3UWGRHr/200w.webp" },
            { english: "print", spanish: "imprimir", points: 0, image: " https://i.giphy.com/media/l2YOxWj7EddS4AZAQ/200w.webp" },
            { english: "belong", spanish: "pertenecer", points: 0, image: " https://i.giphy.com/media/otMNPSShc61Tu6qAjQ/200w.webp" },
            { english: "fasten", spanish: "abrochar", points: 0, image: " https://i.giphy.com/media/BouwBuyFhQwlQYBvmG/200w.webp" },
            { english: "push", spanish: "empujar", points: 0, image: " https://i.giphy.com/media/h7zqTXl02vFPI9BzFo/200w.webp" },
            { english: "bother", spanish: "molestar", points: 0, image: " https://i.giphy.com/media/5UH2PJ8VIEuMqN8V6R/200w.webp" },
            { english: "solve", spanish: "resolver", points: 0, image: " https://i.giphy.com/media/vaKfVsu9zseBy/200w.webp" }
        ]
    },
    {
        name: "4. Verbos Regulares",
        icon: "⚽",
        words: [
            { english: "relieve", spanish: "aliviar", points: 3 },
            { english: "oblige", spanish: "obligar", points: 3 },
            { english: "commit", spanish: "cometer", points: 3 },
            { english: "close", spanish: "cerrar", points: 3 },
            { english: "mention", spanish: "mencionar", points: 3 },
            { english: "believe", spanish: "creer", points: 3 },
            { english: "refer", spanish: "referir", points: 3 },
            { english: "seem", spanish: "parecer", points: 3 },
            { english: "open", spanish: "abrir", points: 3 },
            { english: "weigh", spanish: "pesar", points: 3 },
            { english: "smile", spanish: "sonreír", points: 3 },
            { english: "clean", spanish: "limpiar", points: 3 },
            { english: "acquire", spanish: "adquirir", points: 3 },
            { english: "number", spanish: "numerar", points: 3 },
            { english: "permit", spanish: "permitir", points: 3 },
            { english: "worry", spanish: "preocuparse", points: 3 },
            { english: "please", spanish: "agradar", points: 3 },
            { english: "refuse", spanish: "rehusar", points: 3 },
            { english: "crown", spanish: "coronar", points: 3 },
            { english: "play", spanish: "jugar", points: 3 },
            { english: "include", spanish: "incluir", points: 3 },
            { english: "command", spanish: "mandar", points: 3 },
            { english: "marry", spanish: "casarse", points: 3 },
            { english: "cash", spanish: "cobrar", points: 3 },
            { english: "establish", spanish: "establecer", points: 3 },
            { english: "fish", spanish: "pescar", points: 3 },
            { english: "remove", spanish: "quitar", points: 3 },
            { english: "reach", spanish: "alcanzar", points: 3 },
            { english: "trust", spanish: "confiar", points: 3 },
            { english: "report", spanish: "informar", points: 3 },
            { english: "cross", spanish: "cruzar", points: 3 },
            { english: "fear", spanish: "temer", points: 3 },
            { english: "kiss", spanish: "besar", points: 3 },
            { english: "cease", spanish: "cesar", points: 3 },
            { english: "save", spanish: "ahorrar", points: 3 },
            { english: "use", spanish: "usar", points: 3 },
            { english: "answer", spanish: "contestar", points: 3 },
            { english: "agree", spanish: "acceder", points: 3 },
            { english: "accuse", spanish: "acusar", points: 3 },
            { english: "hate", spanish: "odiar", points: 3 },
            { english: "continue", spanish: "continuar", points: 3 },
            { english: "invite", spanish: "invitar", points: 3 },
            { english: "amount", spanish: "ascender/cantidad", points: 3 },
            { english: "allow", spanish: "permitir", points: 3 },
            { english: "copy", spanish: "copiar", points: 3 },
            { english: "intend", spanish: "proponerse", points: 3 },
            { english: "act", spanish: "actuar", points: 3 },
            { english: "help", spanish: "ayudar", points: 3 },
            { english: "touch", spanish: "tocar", points: 3 },
            { english: "greet", spanish: "saludar", points: 3 }
        ]
    },
    {
        name: "5. Verbos Regulares",
        icon: "🏇",
        words: [
            { english: "justify", spanish: "justificar", points: 3 },
            { english: "dry", spanish: "secar", points: 3 },
            { english: "listen", spanish: "escuchar", points: 3 },
            { english: "advance", spanish: "avanzar", points: 3 },
            { english: "correct", spanish: "corregir", points: 3 },
            { english: "enjoy", spanish: "disfrutar", points: 3 },
            { english: "prepare", spanish: "preparar", points: 3 },
            { english: "esteem", spanish: "estimar", points: 3 },
            { english: "detach", spanish: "separar", points: 3 },
            { english: "annoy", spanish: "molestar", points: 3 },
            { english: "want", spanish: "querer", points: 3 },
            { english: "expect", spanish: "esperar", points: 3 },
            { english: "consist", spanish: "consistir", points: 3 },
            { english: "test", spanish: "probar", points: 3 },
            { english: "absolve", spanish: "absolver", points: 3 },
            { english: "appear", spanish: "aparecer", points: 3 },
            { english: "fetch", spanish: "ir por", points: 3 },
            { english: "guard", spanish: "guardar", points: 3 },
            { english: "wait", spanish: "esperar", points: 3 },
            { english: "contain", spanish: "contener", points: 3 },
            { english: "live", spanish: "vivir", points: 3 },
            { english: "possess", spanish: "poseer", points: 3 },
            { english: "consider", spanish: "considerar", points: 3 },
            { english: "obey", spanish: "obedecer", points: 3 },
            { english: "compose", spanish: "componer", points: 3 },
            { english: "dawn", spanish: "amanecer", points: 3 },
            { english: "attend", spanish: "asistir", points: 3 },
            { english: "wish", spanish: "desear", points: 3 },
            { english: "apologize", spanish: "excusarse", points: 3 },
            { english: "attack", spanish: "atacar", points: 3 },
            { english: "amuse", spanish: "divertir", points: 3 },
            { english: "rain", spanish: "llover", points: 3 },
            { english: "iron", spanish: "planchar", points: 3 },
            { english: "join", spanish: "unir", points: 3 },
            { english: "clear", spanish: "aclarar, limpiar", points: 3 },
            { english: "despise", spanish: "despreciar", points: 3 },
            { english: "sound", spanish: "sonar", points: 3 },
            { english: "damage", spanish: "dañar", points: 3 },
            { english: "kick", spanish: "cocear", points: 3 },
            { english: "stop", spanish: "parar", points: 3 },
            { english: "appoint", spanish: "nombrar", points: 3 },
            { english: "devote", spanish: "dedicar", points: 3 },
            { english: "move", spanish: "mover", points: 3 },
            { english: "reply", spanish: "replicar", points: 3 },
            { english: "drop", spanish: "dejar caer", points: 3 },
            { english: "change", spanish: "cambiar", points: 3 },
            { english: "enclose", spanish: "incluir", points: 3 },
            { english: "guess", spanish: "adivinar", points: 3 },
            { english: "lie", spanish: "mentir", points: 3 },
            { english: "wash", spanish: "lavar", points: 3 }
        ]
    },
    {
        name: "6. Verbos Regulares",
        icon: "🛌",
        words: [
            { english: "tie", spanish: "atar", points: 3 },
            { english: "admire", spanish: "admirar", points: 3 },
            { english: "promise", spanish: "prometer", points: 3 },
            { english: "gather", spanish: "recoger", points: 3 },
            { english: "extract", spanish: "extraer", points: 3 },
            { english: "attempt", spanish: "intentar", points: 3 },
            { english: "improve", spanish: "mejorar", points: 3 },
            { english: "offer", spanish: "ofrecer", points: 3 },
            { english: "evoke", spanish: "evocar", points: 3 },
            { english: "remember", spanish: "recordar", points: 3 },
            { english: "belong", spanish: "pertenecer", points: 3 },
            { english: "mend", spanish: "componer", points: 3 },
            { english: "discover", spanish: "descubrir", points: 3 },
            { english: "avoid", spanish: "evitar", points: 3 },
            { english: "encourage", spanish: "animar", points: 3 },
            { english: "hurry", spanish: "apresurarse", points: 3 },
            { english: "gamble", spanish: "jugar", points: 3 },
            { english: "desire", spanish: "desear", points: 3 },
            { english: "request", spanish: "suplicar, requerir", points: 3 },
            { english: "found", spanish: "fundar", points: 3 },
            { english: "accelerate", spanish: "acelerar", points: 3 },
            { english: "announce", spanish: "anunciar", points: 3 },
            { english: "govern", spanish: "gobernar", points: 3 },
            { english: "organize", spanish: "organizar", points: 3 },
            { english: "drag", spanish: "arrastrar", points: 3 },
            { english: "add", spanish: "sumar", points: 3 },
            { english: "dislike", spanish: "desaprobar", points: 3 },
            { english: "study", spanish: "estudiar", points: 3 },
            { english: "prefer", spanish: "preferir", points: 3 },
            { english: "wound", spanish: "herir", points: 3 },
            { english: "approve", spanish: "aprobar", points: 3 },
            { english: "count", spanish: "contar", points: 3 },
            { english: "affirm", spanish: "afirmar", points: 3 },
            { english: "destroy", spanish: "destruir", points: 3 }
        ]
    },
]




export const seedData = {
    lists
}